# Setup
title:               Sung Chun Lab
tagline:             'tag line'
description:         'Sung Chun Lab is a computational genetics laboratory in the Division of Pulmonary Medicine at <a href="https://www.childrenshospital.org/">Boston Childrens Hospital</a>'
url:                 https://sgchun.github.io/sungchunlab
baseurl:             ''
paginate:            5
permalink:           pretty

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
